language: node_js
node_js: stable
branches:
  only:
  - hexo
# 此处的 hexo 为博客源文件所在的 branch
cache:
  apt: true
  directories:
    - node_modules
before_install:
- git config --global user.name "JamesHopbourn"
- git config --global user.email "jameshopbourn@gmail.com"
# 此处的 user.name 和 user.email 修改为自己的
- npm install -g hexo-cli
install:
- npm i
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://${hexo}@github.com/JamesHopbourn/JamesHopbourn.github.io.git
  master
# 修改 {hexo} 和 push 的地址
- sleep 15
- curl https://api.day.app/oQ3DDZqR3TLmsyLSscVevH/Hexo%20%E5%8D%9A%E5%AE%A2%E6%9B%B4%E6%96%B0%E5%AE%8C%E6%88%90?url=https://jameshopbourn.github.io/
# 修改为你自己 Bark 推送链接