language: node_js
node_js: stable
branches:
  only:
  - hexo
cache:
  apt: true
  directories:
  - node_modules
before_install:
- git config --global user.name "JamesHopbourn"
- git config --global user.email "jameshopbourn@gmail.com"
- npm install -g hexo-cli
install:
- npm i
script:
- hexo clean
- hexo generate
after_success:
- cd  public
- git init
- git add .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://${hexo}@github.com/JamesHopbourn/JamesHopbourn.github.io.git master
- curl ${url}
