# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
  - hexo
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "JamesHopbourn"
- git config --global user.email "jameshopbourn@gmail.com"
# 由于使用了yarn，所以需要下载，如不用yarn这两行可以删除
- npm install -g hexo-cli
install:
- npm i
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force https://${hexo}@github.com/JamesHopbourn/JamesHopbourn.github.io.git
  master
- curl https://api.day.app/oQ3DDZqR3TLmsyLSscVevH/Hexo%20%E5%8D%9A%E5%AE%A2%E6%9B%B4%E6%96%B0%E5%AE%8C%E6%88%90?url=https://jameshopbourn.github.io/